In [2]:
!pip install opendatasets

import opendatasets as od
import pandas as pd

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [3]:
od.download("https://www.kaggle.com/datasets/kazanova/sentiment140")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: abubakarnanaaishah
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/kazanova/sentiment140
Downloading sentiment140.zip to ./sentiment140

100%|██████████| 80.9M/80.9M [00:00<00:00, 1.31GB/s]

In [4]:
df = pd.read_csv('sentiment140/training.1600000.processed.noemoticon.csv',
                 encoding='latin-1',
                 header=None)

In [5]:
print(df.shape[0])
print(df.shape[1])

1600000
6

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   0       1600000 non-null  int64
 1   1       1600000 non-null  int64
 2   2       1600000 non-null  object
 3   3       1600000 non-null  object
 4   4       1600000 non-null  object
 5   5       1600000 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

In [7]:
df_sample = df.sample(n = 10000, random_state = 42).reset_index(drop = True)
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10000 non-null  int64
 1   1       10000 non-null  int64
 2   2       10000 non-null  object
 3   3       10000 non-null  object
 4   4       10000 non-null  object
 5   5       10000 non-null  object
dtypes: int64(2), object(4)
memory usage: 468.9+ KB

In [8]:
!pip install nltk emoji pyspellchecker

import re
import string
from collections import Counter
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from emoji import demojize
from spellchecker import SpellChecker

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting pyspellchecker
  Downloading pyspellchecker-0.8.4-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 9.3 MB/s eta 0:00:00
Downloading pyspellchecker-0.8.4-py3-none-any.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 45.3 MB/s eta 0:00:00
Installing collected packages: pyspellchecker, emoji
Successfully installed emoji-2.15.0 pyspellchecker-0.8.4

In [9]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [10]:
spell = SpellChecker()
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [11]:
df_sample.head()

,0,1,2,3,4,5
0,0,2200003196,Tue Jun 16 18:18:12 PDT 2009,NO_QUERY,LaLaLindsey0609,@chrishasboobs AHHH I HOPE YOUR OK!!!
1,0,1467998485,Mon Apr 06 23:11:14 PDT 2009,NO_QUERY,sexygrneyes,"@misstoriblack cool , i have no tweet apps fo..."
2,0,2300048954,Tue Jun 23 13:40:11 PDT 2009,NO_QUERY,sammydearr,@TiannaChaos i know just family drama. its la...
3,0,1993474027,Mon Jun 01 10:26:07 PDT 2009,NO_QUERY,Lamb_Leanne,School email won't open and I have geography ...
4,0,2256550904,Sat Jun 20 12:56:51 PDT 2009,NO_QUERY,yogicerdito,upper airways problem

In [12]:
df_sample.columns = ['target', 'id', 'date', 'flag', 'user', 'text']

In [13]:
df_sample.head()

,target,id,date,flag,user,text
0,0,2200003196,Tue Jun 16 18:18:12 PDT 2009,NO_QUERY,LaLaLindsey0609,@chrishasboobs AHHH I HOPE YOUR OK!!!
1,0,1467998485,Mon Apr 06 23:11:14 PDT 2009,NO_QUERY,sexygrneyes,"@misstoriblack cool , i have no tweet apps fo..."
2,0,2300048954,Tue Jun 23 13:40:11 PDT 2009,NO_QUERY,sammydearr,@TiannaChaos i know just family drama. its la...
3,0,1993474027,Mon Jun 01 10:26:07 PDT 2009,NO_QUERY,Lamb_Leanne,School email won't open and I have geography ...
4,0,2256550904,Sat Jun 20 12:56:51 PDT 2009,NO_QUERY,yogicerdito,upper airways problem

In [14]:
# finding emoticons

emoticon_regex = r"[:;=8][-~]?[)DdPp(/\(\|\\<>]"

def find_emoticons(text):
    return re.findall(emoticon_regex, str(text))

all_found = []
for tweet in df_sample['text']:
    all_found.extend(find_emoticons(tweet))

emoticon_counts = Counter(all_found)

for emo, count in emoticon_counts.most_common(20):
    print(f"{emo} : used {count} times")

:/ : used 462 times
;) : used 42 times
:| : used 13 times
;p : used 12 times
:p : used 11 times
=D : used 10 times
;-) : used 9 times
;D : used 9 times
;P : used 7 times
;d : used 7 times
=/ : used 6 times
:-D : used 5 times
8p : used 4 times
;( : used 3 times
8d : used 3 times
;/ : used 3 times
:-/ : used 3 times
:-p : used 3 times
=( : used 3 times
=P : used 2 times

In [15]:
#EMOTICONS

EMOTICON_DICT = {
    # Skeptical / Annoyed
    ":/": "skeptical", "=/": "skeptical", ":-/": "skeptical", ";/": "skeptical",

    # Happy / Laughing
    "=d": "laughing", ";d": "laughing", ":-d": "laughing", "8d": "laughing",

    # Wink / Joke
    ";)": "wink", ";-)": "wink",

    # Playful / Tongue Out
    ";p": "playful", ":p": "playful", "=p": "playful", ":-p": "playful", "8p": "playful",

    # Neutral / Bored
    ":|": "neutral",

    # Sad
    ";(": "sad", "=(": "sad"
}

In [16]:
#finding URLs

url_regex = r'https?://\S+|www\.\S+|\S+\.(?:com|net|org|edu|gov|ly|bit|gl|co)\S*'

def find_url(text):
  return re.findall(url_regex, str(text))

all_found = []
for i in df_sample["text"]:
    all_found.extend(find_url(i))

url_count = Counter(all_found)

for url, count in url_count.most_common(100):
    print(f"{url} used {count} times")

www.tweeterfollow.com used 6 times
www.tweeteradder.com used 5 times
http://tweet.sg used 3 times
http://www.4officeautomation.com used 2 times
www.hillsong.co.za used 1 times
http://bit.ly/ec8qJ used 1 times
envirowise.gov.uk used 1 times
http://jijr.com/hitZ used 1 times
chuckishere.com used 1 times
http://bit.ly/4Qhlv used 1 times
http://plurk.com/p/xedq0 used 1 times
http://bit.ly/ueUb6 used 1 times
http://mobypicture.com/?yxykxt used 1 times
http://twitpic.com/6vlkp used 1 times
http://is.gd/M7Q8 used 1 times
http://tr.im/lF45 used 1 times
http://twitpic.com/4eg0i used 1 times
http://budurl.com/beckhams used 1 times
http://www.debbyandchrisryanfansite.webs.com/ used 1 times
http://plurk.com/p/rnauu used 1 times
http://sa9.us/HornySophie used 1 times
http://twitpic.com/6ub7v used 1 times
http://twitpic.com/8cwzd used 1 times
watch...http://tinyurl.com/c8dns8 used 1 times
http://myloc.me/23fl used 1 times
http://tinyurl.com/cfz2lj used 1 times
http://tumblr.com/xgo1z1owl used 1 times
http://plurk.com/p/z2e6x used 1 times
http://yfrog.com/7grxqj used 1 times
http://bit.ly/Ob9HA used 1 times
http://digg.com/d1twJ0 used 1 times
http://twitpic.com/7rish used 1 times
(23)sulumitsretsambew-id.com used 1 times
http://twitpic.com/67z2q used 1 times
fuseboxradio@gmail.com! used 1 times
http://twitpic.com/3tl66 used 1 times
http://blip.fm/~7r7ih used 1 times
http://twitpic.com/5dd11 used 1 times
http://www.geekbrief.tv used 1 times
http://twurl.nl/ynxqkj used 1 times
psykoid.com used 1 times
http://bit.ly/TV22r used 1 times
http://tinyurl.com/deg3ve used 1 times
http://plurk.com/p/swfzh used 1 times
http://twitpic.com/6v42q used 1 times
http://twitpic.com/7s8p5 used 1 times
http://bit.ly/iNjhI used 1 times
http://bit.ly/7S33G used 1 times
http://tinyurl.com/p5nssr used 1 times
http://plurk.com/p/13cyrd used 1 times
http://www.alexandraburkeofficial.com/forums/ used 1 times
http://myloc.me/2hBr used 1 times
http://twitpic.com/6gcq4 used 1 times
http://bit.ly/w1WIR used 1 times
http://tinyurl.com/qq6l3m used 1 times
http://ustre.am/1g6e) used 1 times
http://plurk.com/p/x55cv used 1 times
http://twitpic.com/49c6e used 1 times
whrrl.com? used 1 times
http://bit.ly/JpLJQ used 1 times
http://plurk.com/p/wxonj used 1 times
http://bit.ly/cFgNN used 1 times
http://bit.ly/f7mLH used 1 times
www.TeacherComplaints.com used 1 times
http://twitpic.com/7gqv6 used 1 times
http://www.wowwiki.com/Stinker used 1 times
http://bit.ly/k8idQ used 1 times
http://en.wikipedia.org/wiki/IEDs used 1 times
http://plurk.com/p/11j9b7 used 1 times
http://www.piticu.ro/, used 1 times
bing.com, used 1 times
http://tinyurl.com/axwru used 1 times
http://bit.ly/wJMqn used 1 times
http://cli.gs/3W4jL used 1 times
http://tumblr.com/xjv1ylayt used 1 times
http://plurk.com/p/t0rxk used 1 times
http://tinyurl.com/dzz88m used 1 times
http://bit.ly/rdNz0 used 1 times
omegle.com used 1 times
http://www.mixedcolors.org/ used 1 times
http://tinyurl.com/odqwgh used 1 times
http://twitpic.com/6uohm used 1 times
http://tinyurl.com/dl26wd used 1 times
http://bit.ly/ayViO used 1 times
http://twitpic.com/6m2uh used 1 times
http://twitpic.com/5ezol used 1 times
http://i42.tinypic.com/f4mm2u.jpg used 1 times
http://plurk.com/p/y1of8 used 1 times
http://twitpic.com/69r21 used 1 times
http://bit.ly/MWX6x used 1 times
http://www.paulmellors.net/laconica/index.php used 1 times
http://tinyurl.com/ddyyd6 used 1 times
http://twitpic.com/69f07 used 1 times
http://bit.ly/26bA5u used 1 times
http://bit.ly/CwWbz used 1 times
http://myloc.me/3SY0 used 1 times
anyway...http://bit.ly/CZHD8 used 1 times
http://bit.ly/m7lRb used 1 times
http://twitpic.com/6svwl used 1 times
http://www.flickr.com/photos/nakizm/3631139458/ used 1 times

In [17]:
url_email_regex = r'(\S+@\S+\.\S+)|(https?://\S+|www\.\S+|\S+\.(?:com|net|org|edu|gov|ly|bit|gl|co|me|tv|us)\S*)'

def clean(text):
  text = str(text).lower()

  #Removing emails and url
  text = re.sub(url_email_regex, ' ', text)

  #Replacing emoticons with word
  for emo, word in EMOTICON_DICT.items():
    text = text.replace(emo, f"{word}")

  #Replacing emojis with words
  text = demojize(text).replace(':',' ').replace('_', ' ')

  #Removal of punctuation
  text = text.translate(str.maketrans('', '', string.punctuation))

  #Splitting text into words
  words = text.split()

# (Speed optimization: only check words not in dictionary
  misspelled = spell.unknown(words)
  words = [spell.correction(w) if w in misspelled else w for w in words]
  words = [w for w in words if w is not None] # Remove empty results

  # Removal of Frequent words (Stopwords)
  words = [w for w in words if w not in stop_words]

  # Lemmatization (Base dictionary form)
  words = [lemmatizer.lemmatize(w) for w in words]

  return " ".join(words)

In [18]:
# Removal of Rare and Dataset-wide Frequent words
def remove_extremes(series, freq_limit=100, rare_limit=1):
    all_words = " ".join(series).split()
    counts = Counter(all_words)

    # Identify words that appear too much or only once
    to_remove = set([w for w, c in counts.items() if c > freq_limit or c <= rare_limit])

    return series.apply(lambda x: " ".join([w for w in x.split() if w not in to_remove]))

In [ ]:
from tqdm import tqdm
tqdm.pandas()

df_sample['cleaned_text'] = df_sample['text'].progress_apply(clean)

df_sample['cleaned_text'] = remove_extremes(df_sample['cleaned_text'])

print(df_sample[['text', 'cleaned_text']].head(10))

  6%|▌         | 560/10000 [07:11<52:42,  2.98it/s]